### ISSUE TITLE
Seite weiß

### ISSUE THREAD

**Issue by jkroepke** [r-doener/r-doener.github.io#1]
Moin,

ich wollte die Döner Map besuchen, aber sie geht nicht

Im Chrome und Edge gehts dazu folgenen Fehler in der Browser Console:

![image](https://github.com/r-doener/r-doener.github.io/assets/1560587/f48201c4-895c-45eb-82c7-2ed81c7f0040)

der führt hier hin:

![image](https://github.com/r-doener/r-doener.github.io/assets/1560587/6cfcb912-5634-4b4a-ba8d-e294764a0cf8)

**Comment by r-doener** [comment]
Danke. Checke ich

Grüße,
Georg

-von einem Mobilgerät gesendet -


________________________________
Von: Jan-Otto Kröpke ***@***.***>
Gesendet: Wednesday, April 10, 2024 4:53:13 PM
An: r-doener/r-doener.github.io ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [r-doener/r-doener.github.io] Seite weiß (Issue #1)


Moin,

ich wollte die Döner Map besuchen, aber sie geht nicht

Im Chrome und Edge gehts dazu folgenen Fehler in der Browser Console:

image.png (view on web)<https://github.com/r-doener/r-doener.github.io/assets/1560587/f48201c4-895c-45eb-82c7-2ed81c7f0040>

der führt hier hin:

image.png (view on web)<https://github.com/r-doener/r-doener.github.io/assets/1560587/6cfcb912-5634-4b4a-ba8d-e294764a0cf8>

**Comment by r-doener** [comment]
Fixed (kann 5 min dauern bis online)

Grüße,
Georg 

-von einem Mobilgerät gesendet -


________________________________
Von: Georg  ***@***.***>
Gesendet: Wednesday, April 10, 2024 5:35:33 PM
An: r-doener/r-doener.github.io ***@***.***>; r-doener/r-doener.github.io ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [r-doener/r-doener.github.io] Seite weiß (Issue #1)

Danke. Checke ich

Grüße,
Georg Schröjahr
GS Technik GmbH
Schwedenweg 2
59872 Meschede

-von einem Mobilgerät gesendet -


________________________________
Von: Jan-Otto Kröpke ***@***.***>
Gesendet: Wednesday, April 10, 2024 4:53:13 PM
An: r-doener/r-doener.github.io ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [r-doener/r-doener.github.io] Seite weiß (Issue #1)


Moin,

ich wollte die Döner Map besuchen, aber sie geht nicht

Im Chrome und Edge gehts dazu folgenen Fehler in der Browser Console:

image.png (view on web)<https://github.com/r-doener/r-doener.github.io/assets/1560587/f48201c4-895c-45eb-82c7-2ed81c7f0040>

der führt hier hin:

image.png (view on web)<https://github.com/r-doener/r-doener.github.io/assets/1560587/6cfcb912-5634-4b4a-ba8d-e294764a0cf8>

**Comment by r-doener** [comment]
Fixed
